In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("../DataSets/spam.csv")
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [5]:
#df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
data["Spam"] = data.Category.map({"ham":0, "spam":1})

In [16]:
data.drop(["Category"], inplace = True, axis=1)

KeyError: "['Category'] not found in axis"

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data.Message,data.Spam, test_size=0.3)

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count = v.fit_transform(X_train.values)
X_train_count.toarray()[:2]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [32]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?, i have 50% discount coupon with offer',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!',
    'Last day of offer upto 20%'
]
emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1, 1], dtype=int64)

In [59]:
len(v.get_feature_names())

7195

## CountVectorizer

In [61]:
emails = [
    'Hi, how are you',
    'Upto 20% discount',
    'Last day of offer upto 20%'
]
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
text = vectorizer.fit_transform(emails)  # This converts Text to numbers
print(vectorizer.get_feature_names())
print(text.toarray())

['20', 'are', 'day', 'discount', 'hi', 'how', 'last', 'of', 'offer', 'upto', 'you']
[[0 1 0 0 1 1 0 0 0 0 1]
 [1 0 0 1 0 0 0 0 0 1 0]
 [1 0 1 0 0 0 1 1 1 1 0]]


In [62]:
pd.DataFrame(text.toarray(), columns=cv.get_feature_names())

20  are  day  discount  hi  how  last  of  offer  upto  you
0   0    1    0         0   1    1     0   0      0     0    1
1   1    0    0         1   0    0     0   0      0     1    0
2   1    0    1         0   0    0     1   1      1     1    0

In [63]:
len(vectorizer.get_feature_names())

11