In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
dat = pd.read_csv("run_or_walk.csv")

In [3]:
dat.head()

date                time username  wrist  activity  acceleration_x  \
0  2017-6-30  13:51:15:847724020   viktor      0         0          0.2650   
1  2017-6-30  13:51:16:246945023   viktor      0         0          0.6722   
2  2017-6-30  13:51:16:446233987   viktor      0         0          0.4399   
3  2017-6-30  13:51:16:646117985   viktor      0         0          0.3031   
4  2017-6-30  13:51:16:846738994   viktor      0         0          0.4814   

   acceleration_y  acceleration_z  gyro_x  gyro_y  gyro_z  
0         -0.7814         -0.0076 -0.0590  0.0325 -2.9296  
1         -1.1233         -0.2344 -0.1757  0.0208  0.1269  
2         -1.4817          0.0722 -0.9105  0.1063 -2.4367  
3         -0.8125          0.0888  0.1199 -0.4099 -2.9336  
4         -0.9312          0.0359  0.0527  0.4379  2.4922

In [4]:
dat.describe()

wrist      activity  acceleration_x  acceleration_y  \
count  88588.000000  88588.000000    88588.000000    88588.000000   
mean       0.522170      0.500801       -0.074811       -0.562585   
std        0.499511      0.500002        1.009299        0.658458   
min        0.000000      0.000000       -5.350500       -3.299000   
25%        0.000000      0.000000       -0.381800       -1.033500   
50%        1.000000      1.000000       -0.059500       -0.759100   
75%        1.000000      1.000000        0.355500       -0.241775   
max        1.000000      1.000000        5.603300        2.668000   

       acceleration_z        gyro_x        gyro_y        gyro_z  
count    88588.000000  88588.000000  88588.000000  88588.000000  
mean        -0.313956      0.004160      0.037203      0.022327  
std          0.486815      1.253423      1.198725      1.914423  
min         -3.753800     -4.430600     -7.464700     -9.480000  
25%         -0.376000     -0.920700     -0.644825     -1.345125  
50%         -0.221000      0.018700      0.039300      0.006900  
75%         -0.085900      0.888800      0.733700      1.398200  
max          1.640300      4.874200      8.498000     11.266200

In [32]:
X = dat.drop(["username", "date", "time", "activity"], axis=1)

In [33]:
y = dat["activity"]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [36]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(62011, 7) (26577, 7) (62011,) (26577,)


In [37]:
from sklearn.naive_bayes import GaussianNB

In [38]:
model_1 = GaussianNB()

In [39]:
model_1.fit(X_train, y_train)

GaussianNB()

In [40]:
model_1.predict(X_test)

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [41]:
model_1.score(X_test, y_test)

0.9573315272604132

## ~95% accuracy with acceleration values and gyro values as predictor

In [42]:
X = dat.drop(["username", "date", "time", "activity", "gyro_x", "gyro_y", "gyro_z"], axis=1)

In [43]:
y = dat["activity"]

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [45]:
model_2 = GaussianNB()

In [46]:
model_2.fit(X_train, y_train)

GaussianNB()

In [47]:
model_2.predict(X_test)

array([1, 0, 1, ..., 0, 1, 0], dtype=int64)

In [48]:
model_2.score(X_test, y_test)

0.9577830454904617

## Only using Acceleration as predictor performance is as close as using both.

In [49]:
X = dat.drop(["username", "date", "time", "activity", "acceleration_x", "acceleration_y", "acceleration_z"], axis=1)

In [50]:
y = dat["activity"]

In [51]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=25)

In [52]:
model_3 = GaussianNB()

In [53]:
model_3.fit(X_train, y_train)

GaussianNB()

In [54]:
model_3.predict(X_test)

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [55]:
model_3.score(X_test, y_test)

0.6537231440719419

## Performance is not good if we use only gyro as predictor compared to both