In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [48]:
dat = pd.read_csv("../DataSets/Salary_class.csv")
dat.head()

company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [49]:
dat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype 
---  ------                 --------------  ----- 
 0   company                16 non-null     object
 1   job                    16 non-null     object
 2   degree                 16 non-null     object
 3   salary_more_then_100k  16 non-null     int64 
dtypes: int64(1), object(3)
memory usage: 644.0+ bytes


In [50]:
from sklearn.preprocessing import OrdinalEncoder

In [51]:
dat_categorical = dat[["company", "job", "degree"]]
oeObj = OrdinalEncoder()

In [58]:
dat_transformed = oeObj.fit_transform(dat_categorical)
dat_transformed

array([[2., 2., 0.],
       [2., 2., 1.],
       [2., 0., 0.],
       [2., 0., 1.],
       [2., 1., 0.],
       [2., 1., 1.],
       [0., 2., 1.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [1., 2., 0.],
       [1., 2., 1.],
       [1., 0., 0.],
       [1., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.]])

In [55]:
oeObj.categories_

[array(['abc pharma', 'facebook', 'google'], dtype=object),
 array(['business manager', 'computer programmer', 'sales executive'],
       dtype=object),
 array(['bachelors', 'masters'], dtype=object)]

In [56]:
oeObj.feature_names_in_

array(['company', 'job', 'degree'], dtype=object)

In [62]:
X = pd.DataFrame(dat_transformed, columns=dat_categorical.columns)
X

company  job  degree
0       2.0  2.0     0.0
1       2.0  2.0     1.0
2       2.0  0.0     0.0
3       2.0  0.0     1.0
4       2.0  1.0     0.0
5       2.0  1.0     1.0
6       0.0  2.0     1.0
7       0.0  1.0     0.0
8       0.0  0.0     0.0
9       0.0  0.0     1.0
10      1.0  2.0     0.0
11      1.0  2.0     1.0
12      1.0  0.0     0.0
13      1.0  0.0     1.0
14      1.0  1.0     0.0
15      1.0  1.0     1.0

In [63]:
y = dat["salary_more_then_100k"]

In [64]:
y

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [82]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix

In [105]:
trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.2)

In [106]:
dtObj = DecisionTreeClassifier()

In [107]:
dtObj.fit(trainX, trainy)

DecisionTreeClassifier()

In [108]:
dtObj.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': None,
 'splitter': 'best'}

In [109]:
pred_y = dtObj.predict(testX)
pred_y

array([0, 1, 1, 1], dtype=int64)

In [110]:
confusion_matrix(testy, dtObj.predict(testX))

array([[1, 1],
       [0, 2]], dtype=int64)

In [111]:
pd.DataFrame({"pred_y":pred_y, "testy":testy})

pred_y  testy
6        0      0
3        1      1
8        1      0
11       1      1