https://www.kaggle.com/code/prashant111/decision-tree-classifier-tutorial/data?select=car_evaluation.csv

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [26]:
data = pd.read_csv("DataSets/car_evaluation.csv")
data.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [29]:
data.columns = ["BuyingPrice", "MaintenanceCost", "NumberOfDoors", 
                                    "NumberOfPersons", "Lug_boot", "Safety", "Decision"]
data

BuyingPrice MaintenanceCost NumberOfDoors NumberOfPersons Lug_boot  \
0          vhigh           vhigh             2               2    small   
1          vhigh           vhigh             2               2    small   
2          vhigh           vhigh             2               2      med   
3          vhigh           vhigh             2               2      med   
4          vhigh           vhigh             2               2      med   
...          ...             ...           ...             ...      ...   
1722         low             low         5more            more      med   
1723         low             low         5more            more      med   
1724         low             low         5more            more      big   
1725         low             low         5more            more      big   
1726         low             low         5more            more      big   

     Safety Decision  
0       med    unacc  
1      high    unacc  
2       low    unacc  
3       med    unacc  
4      high    unacc  
...     ...      ...  
1722    med     good  
1723   high    vgood  
1724    low    unacc  
1725    med     good  
1726   high    vgood  

[1727 rows x 7 columns]

In [30]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   BuyingPrice      1727 non-null   object
 1   MaintenanceCost  1727 non-null   object
 2   NumberOfDoors    1727 non-null   object
 3   NumberOfPersons  1727 non-null   object
 4   Lug_boot         1727 non-null   object
 5   Safety           1727 non-null   object
 6   Decision         1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [34]:
# Split X and y
X = data.iloc[:,:-1]
y = data["Decision"]

In [37]:
# Split Test and Training data
from sklearn.model_selection import train_test_split

In [38]:
train_X, test_X, train_y, test_y = train_test_split(X, y, test_size=0.3)

In [39]:
print(train_X.shape, test_X.shape, train_y.shape, test_y.shape)

(1208, 6) (519, 6) (1208,) (519,)


# Encode categorical variables

In [74]:
from sklearn.preprocessing import OrdinalEncoder

In [46]:
OrdEncObj = OrdinalEncoder()

In [77]:
train_X_encoded = OrdEncObj.fit_transform(train_X)
test_X_encoded = OrdEncObj.transform(test_X)

In [79]:
print(train_X_encoded, test_X_encoded)

[[1. 1. 2. 2. 0. 2.]
 [0. 3. 3. 2. 1. 2.]
 [3. 0. 2. 2. 0. 0.]
 ...
 [2. 2. 3. 1. 0. 1.]
 [0. 3. 2. 0. 2. 1.]
 [0. 1. 0. 1. 2. 0.]] [[3. 2. 0. 1. 2. 1.]
 [1. 2. 3. 2. 2. 1.]
 [2. 1. 3. 2. 1. 2.]
 ...
 [1. 0. 3. 0. 2. 2.]
 [2. 0. 3. 1. 2. 2.]
 [3. 0. 1. 1. 0. 1.]]


In [70]:
OrdEncObj.inverse_transform(s)

array([['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ['vhigh', 'vhigh', '2', '2', 'med', 'low'],
       ...,
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [40]:
from sklearn.tree import DecisionTreeClassifier

In [116]:
decisionTreeObj = DecisionTreeClassifier(max_depth=8, random_state=0)

In [117]:
decisionTreeObj.fit(train_X_encoded, train_y)

DecisionTreeClassifier(max_depth=8, random_state=0)

In [118]:
predicted_y = decisionTreeObj.predict(test_X_encoded)

In [119]:
from sklearn.metrics import confusion_matrix

In [120]:
confusion_matrix(test_y, predicted_y)

array([[100,   8,   5,   3],
       [  4,  16,   0,   1],
       [  8,   1, 353,   0],
       [  2,   0,   0,  18]], dtype=int64)

In [121]:
from sklearn.metrics import accuracy_score
print('Model accuracy score {0:0.4f}'. format(accuracy_score(test_y, predicted_y)))

Model accuracy score 0.9383


In [122]:
print('Training set score: {:.4f}'.format(decisionTreeObj.score(train_X_encoded, train_y)))

Training set score: 0.9503


In [123]:
print('Training set score: {:.4f}'.format(decisionTreeObj.score(test_X_encoded, test_y)))

Training set score: 0.9383


In [124]:
# Not sure whether there is over fitting or not.

In [125]:
from sklearn.metrics import classification_report

In [127]:
print(classification_report(test_y, predicted_y))

              precision    recall  f1-score   support

         acc       0.88      0.86      0.87       116
        good       0.64      0.76      0.70        21
       unacc       0.99      0.98      0.98       362
       vgood       0.82      0.90      0.86        20

    accuracy                           0.94       519
   macro avg       0.83      0.87      0.85       519
weighted avg       0.94      0.94      0.94       519

